# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -Iinclude -g

# Target executable
TARGET = dds

# Source files
SRC = transport/transport_tcp.c discovery_daemon/discovery.c

# Object files (autogenerated from SRC)
OBJ = $(SRC:.c=.o)

# Include directories
INCLUDES = -I./transport -I./discovery_daemon

# Build target
all: $(TARGET)

# Link object files to create the target executable
$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $^

# Compile source files into object files
%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

# Clean up build artifacts
clean:
	rm -f $(TARGET) $(OBJ)

# Phony targets
.PHONY: all clean